# Generated by Django 2.2.1 on 2020-02-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], default=1),
        ),
    ]
