# Generated by Django 2.2.1 on 2020-02-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_userinfo_depart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='depart',
        ),
    ]
