# Generated by Django 2.2.1 on 2020-02-19 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20181112_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultrecord',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'pk': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='跟进人'),
        ),
    ]
