# Generated by Django 2.2.1 on 2020-01-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_delete_author2book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='app01.Author'),
        ),
    ]
