# Generated by Django 2.2.1 on 2020-01-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Class_grade',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teach_class',
            fields=[
                ('tcid', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Class')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Scoree',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Class_grade'),
        ),
    ]
