# Generated by Django 2.2.1 on 2020-01-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_author_author2book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author2Book',
        ),
    ]
